version: 2.1

workflows:
  test-flow:
    jobs:
      - app-test

jobs:
  app-test:
    docker:
      - image: cimg/node:19.2.0
    steps:
      - checkout
      - run:
          name: Install Deps
          command: yarn install
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Build App
          command: yarn build