version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:19.2.0
    steps:
      - checkout
      - run:
          name: Install Deps
          command: yarn install
      - run:
          name: Run tests
          command: yarn test
  build:
    docker:
      - image: cimg/node:19.2.0
    steps:
      - checkout
      - run:
          name: Install Deps
          command: yarn install
      - run:
          name: Build App
          command: yarn build
  deploy:
    docker:
      - image: cimg/node:19.2.0
    steps:
      - checkout
      - run:
          name: Deploy App
          command: echo "I am being deployed"

workflows:
  version: 2
  scheduled-flow:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
      - build
      - deploy